networks:
  app:
    driver: bridge

volumes:
  mongo_data:

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.back
    ports:
      - 3000:3000
    environment:
      - HTTP_PORT=3000
      - MONGO_URL=mongodb://mongo:27017/my-mongo
      - JWT_SECRET=ad5c3c32b777914b6115e80c0c02e2dc9c11ec0a7f6455db24c3790aadfd9b50
      - JWT_EXPIRES=31536000
    networks:
      - app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.front
    ports:
      - 5173:4173
    #volumes:
     # - ./frontend:/app
    environment:
      - VITE_MAIN_URL=http://backend:3000/api
      - VITE_SERVER_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - app

